name: taif
description: "مُحرر لغة ألف"
version: 1.1.0

environment:
    sdk: ">=3.11.0 <4.0.0"

dependencies:
    code_forge: ^9.8.0
    file_saver: ^0.3.1
    flutter:
        sdk: flutter
    flutter_code_editor: ^0.3.5
    flutter_localizations:
        sdk: flutter
    highlight: ^0.7.0
    http: ^1.6.0
    input_quantity: ^2.5.2
    lucide_icons_flutter: ^3.1.9
    ota_update: ^7.1.0
    package_info_plus: ^9.0.0
    path_provider: ^2.1.5
    permission_handler: ^12.0.1
    provider: ^6.1.5+1
    re_highlight: ^0.0.3
    shared_preferences: ^2.5.4
    url_launcher: ^6.3.2

dev_dependencies:
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/aliflang/
        - assets/aliflang/arm64-v8a/libalif.so
        - assets/aliflang/arm64-v8a/libc++_shared.so
        - assets/aliflang/library/
        - assets/aliflang/linux/amd64

    fonts:
        - family: Tajawal
          fonts:
              - asset: assets/Tajawal.ttf

flutter_intl:
    enabled: true
